import math

WIDTH, HEIGHT = 640, 480
RESOLUTION = (WIDTH, HEIGHT)
FPS = 30
FOV = math.pi / 3  # 60 degrees
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20
